### ISSUE TITLE
Self update functionality

### ISSUE THREAD

**Issue by LukeTowers** [bennothommo/october-cli#1]
Would be pretty wicked if the tool could have a flag to update itself automatically from github releases.

**Comment by bennothommo** [comment]
Awesome idea.

**Comment by bennothommo** [comment]
Implemented in https://github.com/bennothommo/october-cli/commit/96cf2074ee0c8b3d95ac9f6c1f5b42d4a79d7e12.

**Comment by LukeTowers** [comment]
Wicked awesome dude :)
